### PR TITLE
DMG cookbook bump ~> 2.3

### PR DESCRIPTION
**Pull request by Sauraus**

### CODE REVIEW

**Comment by RoboticCheese** [comment]
Was there a bug in 2.2 that requires the version bump? It seems to still work okay against 2.2.x in my (admittedly brief) testing.

**Comment by Sauraus** [comment]
No bug, however the existing version constraint of ~> 2.2 prevented convergence of systems that depended on the 2.3.x release of the dmg cookbook.

IMHO the dmg cookbook should not be version constrained at all in this cookbook.

**Comment by RoboticCheese** [comment]
It shouldn't be preventing that. `~> 2.2` equates to anything >= 2.2 and < 3.0, under the assumption the dmg authors will roughly adhere to semver and only cut a 3.0 when there's a backwards-incompatible change.

I checked via Berkshelf and it correctly pulled in 2.3.0.

```
$ berks vendor

Resolving cookbook dependencies...
Fetching 'chef-dk' from source at .
Fetching cookbook index from https://supermarket.chef.io...
Using chef-dk (3.1.1) from source at .
Using dmg (2.3.0)
```

What error were you seeing when trying to converge with 2.3.0?

**Comment by Sauraus** [comment]
Version constraint error, when converging a node that depends on another cookbook that depends on dmg 2.3.1 (https://github.com/Sauraus/dmg/tree/pending).

**Comment by RoboticCheese** [comment]
I whipped up a quick [test cookbook](https://gist.github.com/RoboticCheese/61a377a6c8cee53d3c73), using the latest (3.1.0) of chef-dk and 2.3.1 from that branch of dmg. Berkshelf pulled in what it was supposed to and Chef converged successfully.

Also skimmed through the Chef changelog in case there was a version constraint bug fixed recently, but didn't see anything.

Not sure what else to check, but it _should_ just work with dmg 2.3.1 as-is, unless there's a conflicting version constraint somewhere or a Chef bug that I haven't yet been able to reproduce.

**Comment by Sauraus** [comment]
I am pretty sure its a version constraint on dmg elsewhere in my stack that is causing the problem, my system cannot run with anything but my custom dmg 2.3.1.

But the real question is does the chefdk cookbook need a version constraint on dmg at all?

**Comment by RoboticCheese** [comment]
Depends how strongly you believe in semantic versioning. In theory, one day, a dmg 3.0 will be released with changes that aren't backwards compatible. If this isn't pinned to 2.x, Chef runs would potentially start breaking. If it is pinned, it can be tested against 3.0 first and the pin updated when it's known to work.

**Pull request closed without merging**
